export const UNIT_ATTACK_WINDUP_MS = 120;
export const UNIT_ATTACK_LUNGE_MS = 180;
export const UNIT_ATTACK_RECOVER_MS = 220;
export const UNIT_ATTACK_IMPACT_MS = UNIT_ATTACK_WINDUP_MS + UNIT_ATTACK_LUNGE_MS;
export const UNIT_ATTACK_TOTAL_MS =
  UNIT_ATTACK_WINDUP_MS + UNIT_ATTACK_LUNGE_MS + UNIT_ATTACK_RECOVER_MS;

export const UNIT_HIT_RECOIL_MS = 320;
