name: Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Prepare docs artifacts
        run: |
          rm -rf docs
          mkdir -p docs
          cp -R dist/* docs/
          cp docs/index.html docs/404.html
          touch docs/.nojekyll
      - name: Smoke checks
        run: npm run test
      - name: Commit docs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git diff --staged --quiet || git commit -m "chore(docs): update docs"
          git push
