name: Pages (docs/)

on:
  push:
    branches: [ main ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    needs: [ verify-pages ]  # <-- hard dependency on CI job
    if: ${{ needs.verify-pages.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: true }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npm run build

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -R dist/* docs/
          cp dist/index.html docs/404.html
          touch docs/.nojekyll

      - name: Commit docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pages): publish dist → docs"
          file_pattern: docs/*
