name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Determine public base path
        run: |
          if [ -f public/CNAME ]; then
            echo "PUBLIC_BASE_PATH=/" >> "$GITHUB_ENV"
          else
            echo "PUBLIC_BASE_PATH=/${{ github.event.repository.name }}/" >> "$GITHUB_ENV"
          fi
      - name: Build project
        run: npm run build
      - name: Smoke-check dist output
        run: |
          test -f dist/index.html
          TITLE=$(grep -o '<title>.*</title>' dist/index.html || true)
          if [ -z "$TITLE" ]; then
            echo 'dist/index.html is missing a <title> element'
            exit 1
          fi
          test -f dist/404.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: site-dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site-dist
